# Generated by Django 5.0.3 on 2024-03-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogue_app.gender'),
        ),
    ]
