# Generated by Django 5.0.3 on 2024-03-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0002_gender_alter_animal_age_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
