# Generated by Django 5.0.3 on 2024-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
